[debug] [2023-09-23T22:32:29.580Z] ----------------------------------------------------------------------
[debug] [2023-09-23T22:32:29.583Z] Command:       /home/tejas/node_modules/node/bin/node /home/tejas/.nvm/versions/node/v16.13.2/bin/firebase emulators:start
[debug] [2023-09-23T22:32:29.583Z] CLI Version:   12.5.4
[debug] [2023-09-23T22:32:29.584Z] Platform:      linux
[debug] [2023-09-23T22:32:29.584Z] Node Version:  v16.20.2
[debug] [2023-09-23T22:32:29.584Z] Time:          Sun Sep 24 2023 04:02:29 GMT+0530 (India Standard Time)
[debug] [2023-09-23T22:32:29.585Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-09-23T22:32:29.688Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-09-23T22:32:29.688Z] > authorizing via signed-in user (maniyary150@gmail.com)
[info] i  emulators: Shutting down emulators. {"metadata":{"emulator":{"name":"hub"},"message":"Shutting down emulators."}}
[debug] [2023-09-23T22:32:34.712Z] Error: Timed out.
    at Timeout._onTimeout (/home/tejas/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/lib/utils.js:254:49)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[error] 
[error] Error: An unexpected error has occurred.
